name: Manual Build & Health Check

on:
  workflow_dispatch:

jobs:

  prepare:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


  setup-dotnet:
    needs: prepare
    runs-on: windows-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'


  restore:
    needs: setup-dotnet
    runs-on: windows-latest
    steps:
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./apicrud


  build:
    needs: restore
    runs-on: windows-latest
    steps:
      - name: Build project
        run: dotnet build --configuration Release
        working-directory: ./apicrud


  publish:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Publish project
        run: dotnet publish -c Release -o publish
        working-directory: ./apicrud


  deploy:
    needs: publish
    runs-on: windows-latest
    steps:
      - name: Run project
        run: |
          Start-Process dotnet -ArgumentList "apicrud/publish/apicrud.dll --urls=http://serviceproazurefunction.runasp.net/"

      - name: Wait for app
        run: Start-Sleep -Seconds 15


  health-check:
    needs: deploy
    runs-on: windows-latest
    steps:
      - name: Health Check
        run: |
          $response = Invoke-WebRequest http://serviceproazurefunction.runasp.net/health -UseBasicParsing
          if ($response.StatusCode -ne 200) {
            exit 1
          }
