name: Manual Build & Health Check

on:
  workflow_dispatch:

jobs:

  prepare:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'


  build:
    needs: prepare
    runs-on: windows-latest
    steps:
      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release


  upload_results:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Publish project
        run: dotnet publish -c Release -o publish


  cleanup:
    needs: upload_results
    runs-on: windows-latest
    steps:
      - name: Run project
        run: |
          Start-Process dotnet -ArgumentList "publish/apicrud.dll --urls=http://serviceproazurefunction.runasp.net/"

      - name: Wait for app to start
        run: Start-Sleep -Seconds 15

      - name: Health Check
        run: |
          $response = Invoke-WebRequest http://serviceproazurefunction.runasp.net/health -UseBasicParsing
          if ($response.StatusCode -ne 200) {
            exit 1
          }
